spring:
  profiles:
    active: local
---
spring:
  session:
    store-type: jdbc
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: kakaopay
logging:
  level:
    com.spring-jwt-server: TRACE
---
# local 환경
spring:
  profiles: local
  devtools:
    restart:
      enabled: true
      additional-paths: classpath:/
    livereload:
      enabled: true
  jpa:
    show_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    hikari:
      generate-unique-name: false
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: 6lueparr0t
  jwt:
    secret: ENC(EEGopae3rh1QA/6zpkshRGPIhdyHR2cYkbEqsPFqqyw=)
server:
  port: 8080